# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'swiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftProject

  target 'swiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
